# Generated by Django 6.0.2 on 2026-04-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='SmartGuard AI', max_length=100)),
                ('store_name', models.CharField(default='FairPrice Supermarket', max_length=200)),
                ('timezone', models.CharField(default='Asia/Manila', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('session_timeout_minutes', models.IntegerField(default=30)),
                ('email_alerts_enabled', models.BooleanField(default=True)),
                ('sms_alerts_enabled', models.BooleanField(default=False)),
                ('alert_email', models.EmailField(blank=True, default='admin@fairprice.com', max_length=254)),
                ('alert_phone', models.CharField(blank=True, default='', max_length=20)),
                ('notify_on_critical', models.BooleanField(default=True)),
                ('notify_on_high', models.BooleanField(default=True)),
                ('notify_on_medium', models.BooleanField(default=False)),
                ('notify_on_low', models.BooleanField(default=False)),
                ('ai_model', models.CharField(default='YOLOv5s', max_length=20)),
                ('frame_rate', models.IntegerField(default=15)),
                ('confidence_threshold', models.IntegerField(default=65)),
                ('loitering_duration', models.IntegerField(default=60)),
                ('concealment_zones', models.JSONField(blank=True, default=list)),
                ('enabled_behaviors', models.JSONField(blank=True, default=dict, help_text='e.g. {SHOPLIFTING: true, CONCEALMENT: true, LOITERING: true}')),
                ('auto_create_evidence', models.BooleanField(default=True)),
                ('max_failed_logins', models.IntegerField(default=3)),
                ('lockout_duration_minutes', models.IntegerField(default=2)),
                ('require_strong_password', models.BooleanField(default=True)),
                ('log_retention_days', models.IntegerField(default=30)),
                ('auto_backup', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(default='daily', max_length=10)),
                ('backup_time', models.CharField(default='02:00', max_length=5)),
                ('backup_retention_days', models.IntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
