# Generated by Django 6.0.2 on 2026-06-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='ai_model',
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='motion_gated_detection',
            field=models.BooleanField(default=True),
        ),
    ]
