# Generated by Django 6.0.2 on 2026-06-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_systemconfig_clip_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='concealment_zones',
        ),
    ]
