# Generated by Django 6.0.2 on 2026-03-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fix_ops_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='token_type',
            field=models.CharField(choices=[('LOGIN', '2FA Login'), ('RESET', 'Password Reset')], default='LOGIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='E.164 format (+63XXXXXXXXXX). Used by Twilio for SMS alerts.', max_length=20),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
