# Generated by Django 6.0.2 on 2026-06-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otptoken_token_type_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dpa_consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
