import { useEffect, useState } from "react";
import { getWeeklyReport } from "../api/alertApi.js";
import { useAuth } from "../context/AuthContext.jsx";
import "./WeeklyReport.css";

export default function WeeklyReport() {
  const { token } = useAuth();
  const [reportData, setReportData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function fetchReport() {
      try {
        const data = await getWeeklyReport(token);
        setReportData(data);
        setTimeout(() => {
          window.print();
        }, 1000);
      } catch (err) {
        console.error(err);
        setError("Failed to generate report.");
      }
    }
    if (token) fetchReport();
  }, [token]);

  if (error) return <div className="wr-error">{error}</div>;
  if (!reportData) return <div className="wr-loading">Generating Report...</div>;

  const { date_range, alerts, evidence } = reportData;

  return (
    <div className="wr-container">
      <header className="wr-header">
        <h1>SmartGuard Weekly Statistics Report</h1>
        <p>
          <strong>Period:</strong> {new Date(date_range.start).toLocaleDateString()} to {new Date(date_range.end).toLocaleDateString()}
        </p>
      </header>

      <section className="wr-section">
        <h2>Executive Summary</h2>
        <div className="wr-stats-grid">
          <div className="wr-stat-box">
            <h3>Total Alerts</h3>
            <div className="wr-stat-val">{alerts.this_week}</div>
            <div className="wr-stat-sub">Last week: {alerts.last_week}</div>
          </div>
          <div className="wr-stat-box">
            <h3>New Evidence Clips</h3>
            <div className="wr-stat-val">{evidence.this_week}</div>
            <div className="wr-stat-sub">Last week: {evidence.last_week}</div>
          </div>
        </div>
      </section>

      <section className="wr-section">
        <h2>Alert Breakdown by Category</h2>
        <table className="wr-table">
          <thead>
            <tr>
              <th>Category</th>
              <th>Count</th>
            </tr>
          </thead>
          <tbody>
            {Object.entries(alerts.category_breakdown).length === 0 ? (
              <tr><td colSpan="2">No alerts this week</td></tr>
            ) : (
              Object.entries(alerts.category_breakdown).map(([cat, count]) => (
                <tr key={cat}>
                  <td>{cat}</td>
                  <td>{count}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </section>

      <section className="wr-section">
        <h2>Alert Resolution Status</h2>
        <table className="wr-table">
          <thead>
            <tr>
              <th>Status</th>
              <th>Count</th>
            </tr>
          </thead>
          <tbody>
            {Object.entries(alerts.status_breakdown).length === 0 ? (
              <tr><td colSpan="2">No status changes this week</td></tr>
            ) : (
              Object.entries(alerts.status_breakdown).map(([stat, count]) => (
                <tr key={stat}>
                  <td>{stat}</td>
                  <td>{count}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </section>

      <footer className="wr-footer">
        Generated by SmartGuard AI Detection System on {new Date().toLocaleString()}
      </footer>
    </div>
  );
}
