# Generated by Django 6.0.2 on 2026-04-24 10:39

import django.db.models.deletion
import evidence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0004_alert_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=evidence.models.evidence_upload_path)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('duration_seconds', models.FloatField(default=30.0)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('fps', models.FloatField(default=15.0)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('integrity_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('ERROR', 'Error')], default='PROCESSING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_clips', to='alerts.alert')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert'], name='evidence_ev_alert_i_c0c281_idx'), models.Index(fields=['status'], name='evidence_ev_status_1fee8c_idx'), models.Index(fields=['created_at'], name='evidence_ev_created_475f87_idx')],
            },
        ),
    ]
