# Generated by Django 6.0.2 on 2026-05-07 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alter_alert_behavior_type'),
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceclip',
            name='encryption_iv',
            field=models.CharField(blank=True, help_text='Hex-encoded 12-byte AES-GCM nonce/IV.', max_length=32),
        ),
        migrations.AddField(
            model_name='evidenceclip',
            name='encryption_tag',
            field=models.CharField(blank=True, help_text='Hex-encoded 16-byte AES-GCM authentication tag.', max_length=32),
        ),
        migrations.AddField(
            model_name='evidenceclip',
            name='is_encrypted',
            field=models.BooleanField(default=True, help_text='Whether the clip file is AES-256-GCM encrypted at rest.'),
        ),
        migrations.AddField(
            model_name='evidenceclip',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed Incident'), ('FALSE_POSITIVE', 'False Positive')], default='PENDING', help_text='Admin/OPS review status. PENDING clips auto-expire.', max_length=20),
        ),
        migrations.AddField(
            model_name='evidenceclip',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the clip was reviewed.', null=True),
        ),
        migrations.AddField(
            model_name='evidenceclip',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin or OPS Manager who reviewed this clip.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evidenceclip',
            name='duration_seconds',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddIndex(
            model_name='evidenceclip',
            index=models.Index(fields=['review_status'], name='evidence_ev_review__ac31d0_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceclip',
            index=models.Index(fields=['expires_at'], name='evidence_ev_expires_d8aef8_idx'),
        ),
    ]
