# Generated by Django 6.0.2 on 2026-04-24 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0004_alert_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(choices=[('VERBAL_WARNING', 'Verbal Warning'), ('ITEM_RECOVERED', 'Item Recovered'), ('SUSPECT_DETAINED', 'Suspect Detained'), ('POLICE_CALLED', 'Police Called'), ('CCTV_REVIEWED', 'CCTV Reviewed'), ('NO_ACTION', 'No Action Required'), ('OTHER', 'Other')], default='CCTV_REVIEWED', max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated to Authorities'), ('FALSE_ALARM', 'False Alarm')], default='OPEN', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the incident and response.')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or follow-up information.')),
                ('external_reference', models.CharField(blank=True, help_text='External reference number (e.g. police blotter, barangay report).', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='alerts.alert')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert'], name='ir_incident_alert_i_419d29_idx'), models.Index(fields=['status'], name='ir_incident_status_363bca_idx'), models.Index(fields=['responder'], name='ir_incident_respond_e7ee6e_idx'), models.Index(fields=['created_at'], name='ir_incident_created_367de1_idx')],
            },
        ),
    ]
