# Generated by Django 6.0.2 on 2026-02-19 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_category',
            field=models.CharField(choices=[('SHOPLIFTING', 'Shoplifting / Behavioral'), ('SYSTEM_SECURITY', 'System / Cybersecurity')], default='SHOPLIFTING', max_length=30),
        ),
        migrations.AlterField(
            model_name='alert',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('ESCALATED', 'Escalated'), ('FALSE_POSITIVE', 'False Positive'), ('CLOSED', 'Closed')], default='NEW', max_length=20),
        ),
    ]
