# Generated by Django 6.0.2 on 2026-04-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='snapshots/%Y/%m/%d/'),
        ),
    ]
