# Generated by Django 6.0.2 on 2026-05-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_add_alert_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='behavior_type',
            field=models.CharField(choices=[('LOITERING', 'Loitering'), ('CONCEALMENT', 'Concealment'), ('RAPID_EXIT', 'Rapid Exit'), ('SHOPLIFTING', 'Shoplifting')], max_length=20),
        ),
    ]
