# Generated by Django 6.0.2 on 2026-02-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='last_heartbeat',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='location',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='name',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='status',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='zone',
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.URLField(max_length=500),
        ),
    ]
