# Generated by Django 6.0.2 on 2026-02-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_remove_camera_is_active_remove_camera_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='camera',
            name='name',
            field=models.CharField(default='Default camera', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('ERROR', 'Error')], default='OFFLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='camera',
            name='zone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
