# Generated by Django 6.0.2 on 2026-02-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camera_is_active_camera_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(max_length=500),
        ),
    ]
