# Generated by Django 6.0.2 on 2026-02-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002 camera stream mjpeg url'),
        ('cameras', '0004_alter_camera_rtsp_url'),
    ]

    operations = [
    ]
